### ISSUE TITLE
Metadata for paths config file

### ISSUE THREAD

**Issue by GeospatialDaryl** [BrandtH22/Rhizosphere#4]
Hi- 
Thanks for your effort - I'm looking at translating your windows specific parts to Linux standards.   What are the three rows in the config file?

**Comment by BrandtH22** [comment]
Hey GeospatialDaryl, I assume you are referring to the defaults file. That contains an array of the file paths in the following order: PowerShell file, virtual environment, Chialisp. It was added mainly because I have not updated the code to eliminate the need for the separate ps fine and virtual environment.

Do let me know if I missed anything and I look forward to seeing the Linux port! Thank you!
